on:
  schedule:
    # Every 5:30 AM in the morning UTC
    - cron: '30 5 * * *'
  workflow_dispatch: {}

name: "Every day"

jobs:
  checkAsdfUpdatesPython:
    name: "Update asdf Python"

    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: swappiehq/github-actions/actions/update-python@main
  checkAsdfUpdatesNode:
    name: "Update asdf NodeJS"
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: swappiehq/github-actions/actions/update-nodejs@main