on:
  schedule:
    # Every 5 AM in the morning UTC
    - cron: '0 5 * * * *'
  workflow_dispatch: {}

name: "Every fifteen minutes"

jobs:
  checkAsdfUpdatesPython:
    name: "ASDF Update Python"

    permissions:
      contents: write
      pull-requests: write

    uses: ./.github/workflows/part_asdf_update.yml
    with:
      plugin: "python"
      release_notes: "https://docs.python.org/$MAJOR_VERSION/whatsnew/changelog.html#python-$LATEST_VERSION_WITH_DASHES-final"