on:
  schedule:
    # Every 5:30 AM in the morning UTC
    - cron: '30 5 * * *'
  workflow_dispatch: {}

name: "Update asdf and Dockerfile versions"

jobs:
  UpdatesAsdfPython:
    name: "Update asdf Python"
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: swappiehq/github-actions/update-python@main
        with:
          version: major-updates
  UpdatesAsdfNode:
    name: "Update asdf NodeJS"
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: swappiehq/github-actions/update-nodejs@main
        with:
          version: minor-updates