on:
  schedule:
    # Every 5:30 AM in the morning UTC
    - cron: '30 5 * * *'
  workflow_dispatch: {}

name: "Every day"

jobs:
  checkAsdfUpdatesPython:
    name: "asdf Update Python"

    permissions:
      contents: write
      pull-requests: write

    uses: swappiehq/github-actions/actions/update-python
  checkAsdfUpdatesNode:
    name: "asdf Update Nodejs"

    permissions:
      contents: write
      pull-requests: write

    uses: swappiehq/github-actions/actions/update-nodejs