on:
  workflow_call:
    inputs:
      plugin:
        type: string
        required: true
      constraint:
        type: string
        default: ""
        required: false
      release_notes:
        type: string
        required: true

name: "ASDF Update"

jobs:
  compile_assets:
    name: "${{ inputs.plugin }}"

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: ASDF Setup plugins
        uses: asdf-vm/actions/plugins-add@master
      - name: Get Newest Version
        id: newestVersion
        run: |
          LATEST_VERSION=$(asdf latest "${{ inputs.plugin }}" "${{ inputs.constraint }}")
          echo "Latest (${{ inputs.constraint }}): $LATEST_VERSION"
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
          MAJOR_VERSION=$(echo LATEST_VERSION | cut -d '.' -f 1,2)
          LATEST_VERSION_WITH_DASHES=$(echo LATEST_VERSION | tr . -)
          eval RELEASE_NOTES="${{ inputs.release_notes }}"
          echo "Realese notes available in: $RELEASE_NOTES"
          echo "RELEASE_NOTES=${RELEASE_NOTES}" >> $GITHUB_ENV
      - name: "Try Installing new version"
        run: |
          asdf install "${{ inputs.plugin }}" "${{ env.LATEST_VERSION }}"
      - name: Apply latest version to .tool-versions
        run: |
          asdf local "${{ inputs.plugin }}" "${{ env.LATEST_VERSION }}"
      - uses: peter-evans/create-pull-request@v4
        with:
          add-paths: '.tool-versions'
          commit-message: 'Update ${{ inputs.plugin }} to ${{ env.LATEST_VERSION }}'
          title: 'Update ${{ inputs.plugin }} to ${{ env.LATEST_VERSION }}'
          branch: 'update/${{ inputs.plugin }}/${{ env.LATEST_VERSION }}'
          body: 'See release notes in: ${{ env.RELEASE_NOTES }}'
          delete-branch: true
          labels: 'update,enhancement'