on:
  workflow_call:
    inputs:
      plugin:
        type: string
        required: true
      release_notes:
        type: string
        required: true
      docker_image:
        type: string
        required: false
        default: ""

name: "ASDF Update"

jobs:
  compile_assets:
    name: "${{ inputs.plugin }}"

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: ASDF Setup plugins
        uses: asdf-vm/actions/plugins-add@master
      - name: Get Newest Version
        id: newestVersion
        run: |
          echo "CURRENT_VERSION=$(grep "^${{ inputs.plugin }}" .tool-versions | cut -d' ' -f2)" >> $GITHUB_ENV
          LATEST_VERSION=$(asdf latest "${{ inputs.plugin }}")
          echo "Updating from $CURRENT_VERSION to $LATEST_VERSION"
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
          MAJOR_VERSION=$(echo $LATEST_VERSION | cut -d '.' -f 1)
          MINOR_VERSION=$(echo $LATEST_VERSION | cut -d '.' -f 1,2)
          LATEST_VERSION_WITH_DASHES=$(echo $LATEST_VERSION | tr . -)
          RELEASE_NOTES=$(eval echo "${{ inputs.release_notes }}")
          echo "RELEASE_NOTES=${RELEASE_NOTES}" >> $GITHUB_ENV
      - name: "Try Installing new version"
        run: |
          asdf install "${{ inputs.plugin }}" "${{ env.LATEST_VERSION }}"
      - name: Apply latest version to .tool-versions
        run: |
          asdf local "${{ inputs.plugin }}" "${{ env.LATEST_VERSION }}"
      - name: Update latest version to Dockerfile too
        run: |
          test -n "${{ inputs.docker_image }}" && test -f Dockerfile && sed -i "s/^FROM ${{ inputs.docker_image }}:${{ env.CURRENT_VERSION }}/FROM ${{ inputs.docker_image }}:${{ env.LATEST_VERSION }}/" Dockerfile
      - uses: peter-evans/create-pull-request@v4
        with:
          add-paths: '.tool-versions,Dockerfile'
          commit-message: 'Update ${{ inputs.plugin }} from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}'
          title: 'Update ${{ inputs.plugin }} from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}'
          branch: 'update/${{ inputs.plugin }}/${{ env.LATEST_VERSION }}'
          body: 'See release notes in: ${{ env.RELEASE_NOTES }}'
          delete-branch: true
          labels: 'update,enhancement'